Repository maplibre/flutter-maplibre-gl, pull requests merged in 2025-09, with the labels that each got.

#614 Expose hovering events
  maplibre_gl/CHANGELOG.md
  maplibre_gl/lib/src/annotation_manager.dart
  maplibre_gl/lib/src/controller.dart
  maplibre_gl/lib/src/global.dart
  maplibre_gl_example/ios/Podfile.lock
  maplibre_gl_example/lib/layer.dart
  maplibre_gl_example/lib/line.dart
  maplibre_gl_example/lib/place_fill.dart
  maplibre_gl_example/lib/place_symbol.dart
  maplibre_gl_platform_interface/lib/src/callbacks.dart
  maplibre_gl_platform_interface/lib/src/maplibre_gl_platform_interface.dart
  maplibre_gl_web/lib/src/interop/util/evented_interop.dart
  maplibre_gl_web/lib/src/maplibre_web_gl_platform.dart
  maplibre_gl_web/lib/src/util/evented.dart
Labels: enhancement, web

#621 Prevented calling notifyListeners() after the controller is disposed.
  maplibre_gl/CHANGELOG.md
  maplibre_gl/lib/src/controller.dart
Labels: bug, next version

#569 Fix offline region download crashing the example app
  maplibre_gl/lib/src/global.dart
  maplibre_gl/lib/src/maplibre_styles.dart
  maplibre_gl_example/lib/offline_regions.dart
Labels: bug
